steps:
- name: 'composer'
  args: ['install']
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'gs://${PROJECT_ID}_build_dropin/*', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
